[package]
name = "xanterella-server"
version = "0.1.0"
edition = "2024"

[dependencies]
xanterella-core = { path = "../core" }

axum = "0.7"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0.149"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.149"
tower = "0.5.3"
