[package]
name = "xanterella-server"
version = "0.1.0"
edition = "2024"

[dependencies]
xanterella-core = { path = "../core" }

axum = "0.7"
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1", features = ["sync"] }
serde_json = "1.0.149"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
