name: Xanterella-Cli CI

on:
  pull_request:
    branches: [ "stable", "testing" ]

jobs:
  build-and-test:
    runs-on: [self-hosted, xanterella]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          clean: false

      - name: Cargo Check
        run: nix develop .#xanterella --command bash -c "cd xanterella && cargo check --release"

      - name: Cargo Tests
        run: nix develop .#xanterella --command bash -c "cd xanterella && cargo test"

      - name: Cargo Build
        run: nix build .#xanterella

      - name: Cleanup
        uses: Swatinem/rust-cache@v2
