name: Xanterella-Cli CI

on:
  pull_request:
    branches: [ "stable" ]

jobs:
  build-and-test:
    runs-on: [self-hosted, xanterella]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Formatierung prüfen
        run: nix develop .#xanterella --command bash -c "cd xanterella && cargo fmt -- --check"

      #- name: Clippy
      #  run: nix develop .#xanterella --command cargo clippy -- -D warnings

      - name: Cargo Tests
        run: nix develop .#xanterella --command bash -c "cd xanterella && cargo test"

      - name: Cargo Build
        run: nix build .#xanterella
