name: Xanterella-Cli CI Stable

on:
  pull_request:
    branches: [ "final/stable", "stable" ]

jobs:
  check-guard:
    name: Check Guard
    uses: ./.github/workflows/branchguard.yml

  flake:
    name: Flake Check (Stable)
    runs-on: [self-hosted, xanterella, fast]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Nix Flake Check 
        run: nix flake check 

  xanterella-start:
    name: Xanterella Start (Stable)
    if: needs.check-guard.outputs.proceed == 'true'
    runs-on: [self-hosted, xanterella]
    needs: 
      - flake

    steps:
      - name: Start 
        run: echo "Starte"

  xanterella-start-test:
    name: Xanterella Start Tests (Stable)
    runs-on: [self-hosted, xanterella]
    needs: 
      - xanterella-start
      - xanterella-machete
      - xanterella-audit
      - xanterella-check
      - xanterella-clippy
      - xanterella-format

    steps:
      - name: Start Tests 
        run: echo "Starte"

  xanterella-machete:
    name: Xanterella Machete (Stable)
    needs: 
      - xanterella-start
    runs-on: [self-hosted, xanterella]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cargo Machete
        run: nix develop .#xanterella --command bash -c "cd xanterella && cargo machete"

  xanterella-audit:
    name: Xanterella Audit (Stable)
    needs:
      - xanterella-start
    runs-on: [self-hosted, xanterella]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cargo Audit
        run: nix develop .#xanterella --command bash -c "cd xanterella && cargo audit"

  xanterella-format:
    name: Xanterella Format (Stable)
    needs:
      - xanterella-start
    runs-on: [self-hosted, xanterella]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cargo Format
        run: nix develop .#xanterella --command bash -c "cd xanterella && cargo fmt --check"

  xanterella-check:
    name: Xanterella Check (Stable)
    needs:
      - xanterella-start
    runs-on: [self-hosted, xanterella]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cargo Check
        run: nix develop .#xanterella --command bash -c "cd xanterella && cargo check --release"

  xanterella-clippy:
    name: Xanterella Clippy (Stable)
    needs:
      - xanterella-start
    runs-on: [self-hosted, xanterella]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cargo Clippy
        run: nix develop .#xanterella --command bash -c "cd xanterella && cargo clippy -- -D warnings"

  xanterella-test:
    name: Xanterella Test (Stable)
    needs:
      - xanterella-start-test
    runs-on: [self-hosted, xanterella]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cargo Test
        run: nix develop .#xanterella --command bash -c "cd xanterella && cargo test -- --include-ignored"

  xanterella-tarpaulin:
    name: Xanterella Tarpaulin (Stable)
    needs:
      - xanterella-start-test
    runs-on: [self-hosted, xanterella]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cargo Tarpaulin
        run: nix develop .#xanterella --command bash -c "cd xanterella && cargo tarpaulin --fail-under 60"

  xanterella-doc:
    name: Xanterella Doc Check (Stable)
    needs:
      - xanterella-start-test
    runs-on: [self-hosted, xanterella]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cargo Doc (Documentation Check)
        run: nix develop .#xanterella --command bash -c "cd xanterella && RUSTDOCFLAGS='-D warnings' cargo doc --no-deps --document-private-items"

  xanterella-build:
    name: Xanterella Build (Stable)
    needs:
      - xanterella-doc
      - xanterella-tarpaulin
      - xanterella-test
    runs-on: [self-hosted, xanterella]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cargo Build
        run: nix build .#xanterella

  prolyxena-start:
    name: Prolyxena Start (Stable)
    if: needs.check-guard.outputs.proceed == 'true'
    runs-on: [self-hosted, prolyxena]
    needs: 
      - flake

    steps:
      - name: Start 
        run: echo "Starte" 

  prolyxena-start-test:
    name: Prolyxena Start Tests (Stable)
    runs-on: [self-hosted, prolyxena]
    needs: 
      - prolyxena-start
      - prolyxena-machete
      - prolyxena-audit
      - prolyxena-check
      - prolyxena-clippy
      - prolyxena-format

    steps:
      - name: Start  
        run: echo "Starte"

  prolyxena-machete:
    name: Prolyxena Machete (Stable)
    needs: 
      - prolyxena-start
    runs-on: [self-hosted, prolyxena]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cargo Machete
        run: nix develop .#prolyxena --command bash -c "cd prolyxena && cargo machete"

  prolyxena-audit:
    name: Prolyxena Audit (Stable)
    needs:
      - prolyxena-start
    runs-on: [self-hosted, prolyxena]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cargo Audit
        run: nix develop .#prolyxena --command bash -c "cd prolyxena && cargo audit"

  prolyxena-format:
    name: Prolyxena Format (Stable)
    needs:
      - prolyxena-start
    runs-on: [self-hosted, prolyxena]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cargo Format
        run: nix develop .#prolyxena --command bash -c "cd prolyxena && cargo fmt --check"

  prolyxena-check:
    name: Prolyxena Check (Stable)
    needs:
      - prolyxena-start
    runs-on: [self-hosted, prolyxena]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cargo Check
        run: nix develop .#prolyxena --command bash -c "cd prolyxena && cargo check --release"

  prolyxena-clippy:
    name: Prolyxena Clippy (Stable)
    needs:
      - prolyxena-start
    runs-on: [self-hosted, prolyxena]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cargo Clippy
        run: nix develop .#prolyxena --command bash -c "cd prolyxena && cargo clippy -- -D warnings"

  prolyxena-test:
    name: Prolyxena Test (Stable)
    needs:
      - prolyxena-start-test
    runs-on: [self-hosted, prolyxena]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cargo Test
        run: nix develop .#prolyxena --command bash -c "cd prolyxena && cargo test -- --include-ignored"

  prolyxena-tarpaulin:
    name: Prolyxena Tarpaulin (Stable)
    needs:
      - prolyxena-start-test
    runs-on: [self-hosted, prolyxena]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cargo Tarpaulin
        run: nix develop .#prolyxena --command bash -c "cd prolyxena && cargo tarpaulin --fail-under 60"

  prolyxena-doc:
    name: Prolyxena Doc Check (Stable)
    needs:
      - prolyxena-start-test
    runs-on: [self-hosted, prolyxena]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cargo Doc (Documentation Check)
        run: nix develop .#prolyxena --command bash -c "cd prolyxena && RUSTDOCFLAGS='-D warnings' cargo doc --no-deps --document-private-items"

  prolyxena-build:
    name: Prolyxena Build (Stable)
    needs:
      - prolyxena-doc
      - prolyxena-tarpaulin
      - prolyxena-test
    runs-on: [self-hosted, prolyxena]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cargo Build
        run: nix build .#prolyxena
