name: Xanterella-Cli CI Staging

on:
  pull_request:
    branches: [ "final/staging" ]

jobs:
  flake: 
    name: Flake Check (Staging)
    runs-on: [self-hosted, xanterella]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Nix Flake Check 
        run: nix flake check 

  xanterella1:
    name: Xanterella Check (Staging)
    runs-on: [self-hosted, xanterella]
    needs: 
      - flake

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cargo Check
        run: nix develop .#xanterella --command bash -c "cd xanterella && cargo check"

  xanterella2:
    name: Xanterella Test (Staging)
    runs-on: [self-hosted, xanterella]
    needs: 
      - xanterella1

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cargo Tests
        run: nix develop .#xanterella --command bash -c "cd xanterella && cargo test"

  xanterella3:
    name: Xanterella Build (Staging)
    runs-on: [self-hosted, xanterella]
    needs: 
      - xanterella1
      - xanterella2

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cargo Build
        run: nix build .#xanterella

  prolyxena1:
    name: Prolyxena Check (Staging)
    runs-on: [self-hosted, xanterella]
    needs: 
      - flake

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cargo Check
        run: nix develop .#prolyxena --command bash -c "cd prolyxena && cargo check"

  prolyxena2:
    name: Prolyxena Test (Staging)
    runs-on: [self-hosted, xanterella]
    needs: 
      - prolyxena1

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cargo Tests
        run: nix develop .#prolyxena --command bash -c "cd prolyxena && cargo test"

  prolyxena3:
    name: Prolyxena Build (Staging)
    runs-on: [self-hosted, xanterella]
    needs: 
      - prolyxena1
      - prolyxena2

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cargo Build
        run: nix build .#prolyxena
